### ISSUE TITLE
Bugged when exiting a level.

### ISSUE THREAD

**Issue by CartoxGD** [cos8oih/GDPerformanceFix#2]
When you exit the first level you play, the performance bugs out. It is fine for the first level, running at a consistent 240 for most levels, but when you get out of the first level and into the next one, it cuts your fps in half for some reason. IDK what causes this but it would be nice to have this fixed.

**Comment by cos8oih** [comment]
I hardly believe the problem is related to this mod. Please make sure other mods you might have installed arent the cause of it.
